#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../test-helpers.sh"

echo "Testing MCP skill gate wording..."

SETUP="$PLUGIN_ROOT/skills/using-supaflow/setup-preamble.md"
ENTRY="$PLUGIN_ROOT/skills/using-supaflow/SKILL.md"
SAFE="$PLUGIN_ROOT/skills/using-supaflow/mcp-safe-executor.md"
WORKFLOWS="$PLUGIN_ROOT/skills/using-supaflow/mcp-workflows.md"

assert_file_contains "$SETUP" "Desktop MCP path" "setup gate: has Desktop MCP path"
assert_file_contains "$SETUP" "mcp__supaflow__auth_status" "setup gate: detects MCP auth tool"
assert_file_contains "$SETUP" "Do NOT fall back to \`Bash(supaflow \\*)\`" "setup gate: blocks Bash fallback in MCP mode"
assert_file_contains "$SETUP" "do NOT suggest plugin \`.mcp.json\`" "setup gate: rejects plugin .mcp.json for Desktop"
assert_file_contains "$SETUP" "Never accept, request, or echo an API key" "setup gate: blocks API keys in chat"

assert_file_contains "$ENTRY" "Prefer MCP when it exists" "entry skill: MCP is preferred surface"
assert_file_contains "$ENTRY" "MCP workflows are authoritative" "entry skill: MCP workflows are authoritative"
assert_file_contains "$ENTRY" "the MCP wrapper still passes the prepared object file internally" "entry skill: guided all-objects behavior is pinned"
assert_file_contains "$ENTRY" "Never paste credential material" "entry skill: blocks credential material"
assert_file_contains "$ENTRY" "MCP approval prompts are not a substitute" "entry skill: MCP approval is not confirmation"
assert_file_contains "$ENTRY" "read \`mcp-safe-executor.md\`" "entry skill: references MCP safe executor"
assert_file_contains "$ENTRY" "read \`mcp-workflows.md\`" "entry skill: references MCP workflows"
assert_file_contains "$ENTRY" "Do not pretend cowork-VM file tools can edit host MCP files" "entry skill: blocks host file edit assumption"

assert_file_contains "$SAFE" "Required sequence for every non-read-only MCP call" "safe executor: has non-read-only sequence"
assert_file_contains "$SAFE" "Read current state first" "safe executor: read before write"
assert_file_contains "$SAFE" "Re-read state after the tool call" "safe executor: verify after write"
assert_file_contains "$SAFE" "MCP approval alone is not confirmation" "safe executor: approval prompt is insufficient"
assert_file_contains "$SAFE" "no dedicated MCP tool performs that exact edit, STOP" "safe executor: host file edit stop condition"
assert_file_contains "$SAFE" "pipelines_prepare_create" "safe executor: classifies guided prepare-create"
assert_file_contains "$SAFE" "refresh_catalog: true.*explicitly asks" "safe executor: refresh catalog requires explicit request"
assert_file_contains "$SAFE" "Credential-bearing outputs" "safe executor: has credential redaction section"
assert_file_contains "$SAFE" "Never paste those values into chat" "safe executor: blocks secret output paste"
assert_file_contains "$SAFE" "pipelines_prepare_create.*pipelines_create_from_plan" "safe executor: prefers guided pipeline creation"
assert_file_contains "$SAFE" "pass \`confirmed: true\` only after" "safe executor: confirmed true requires final confirmation"

assert_file_contains "$WORKFLOWS" "Create pipeline" "mcp workflows: has guided create-pipeline workflow"
assert_file_contains "$WORKFLOWS" "authoritative Desktop MCP workflows" "mcp workflows: authoritative in Desktop MCP mode"
assert_file_contains "$WORKFLOWS" "duplicate-prevention gate" "mcp workflows: preserves duplicate prevention"
assert_file_contains "$WORKFLOWS" "source\\.datasource_id.*destination\\.datasource_id" "mcp workflows: duplicate matching uses nested ids"
assert_file_contains "$WORKFLOWS" "separate pipeline prefix and writes to a separate destination schema" "mcp workflows: duplicate separate pipeline warning"
assert_file_contains "$WORKFLOWS" "mcp__supaflow__pipelines_prepare_create" "mcp workflows: uses guided prepare-create"
assert_file_contains "$WORKFLOWS" "mcp__supaflow__pipelines_create_from_plan" "mcp workflows: uses guided create-from-plan"
assert_file_contains "$WORKFLOWS" "pipeline_prefix.*cannot be changed after creation" "mcp workflows: preserves permanent prefix warning"
assert_file_contains "$WORKFLOWS" "typo check" "mcp workflows: preserves custom prefix typo check"
assert_file_contains "$WORKFLOWS" "re-present the full final config summary" "mcp workflows: re-shows final config after edits"
assert_file_contains "$WORKFLOWS" "object_selection.*mode.*all" "mcp workflows: all objects uses guided MCP selection"
assert_file_contains "$WORKFLOWS" "valid even when \`objects_truncated\` is true" "mcp workflows: all objects allowed for truncated catalogs"
assert_file_contains "$WORKFLOWS" "prepared object file internally" "mcp workflows: guided all-objects uses prepared object file"
assert_file_contains "$WORKFLOWS" "not an exclude list" "mcp workflows: preserves include-list semantics"
assert_file_contains "$WORKFLOWS" "review the host-side \`host_files.objects\` file outside chat" "mcp workflows: truncated subset uses host file review"
assert_file_contains "$WORKFLOWS" "provide the exact \`fully_qualified_name\` values" "mcp workflows: truncated subset requires exact object names"
assert_file_contains "$WORKFLOWS" "ask whether to select all objects instead" "mcp workflows: truncated subset can fall back to all objects"
assert_file_contains "$WORKFLOWS" "Trust \`verification\` over the create-response summary" "mcp workflows: verification is authoritative"
assert_file_contains "$WORKFLOWS" "Check job status" "mcp workflows: has check-job workflow"
assert_file_contains "$WORKFLOWS" "mcp__supaflow__jobs_status" "mcp workflows: uses jobs_status"
assert_file_contains "$WORKFLOWS" "If the list result is truncated" "mcp workflows: pages truncated pipeline lists"
assert_file_contains "$WORKFLOWS" "Explain job failure" "mcp workflows: has explain-failure workflow"
assert_file_contains "$WORKFLOWS" "Do not paste the full log" "mcp workflows: blocks full-log dump"

print_summary
